# Generated by Django 4.2.16 on 2024-10-16 00:32

from django.db import migrations


class Migration(migrations.Migration):
    """
    This is a proxy model that's going to be moved to the vision_backend app.
    """

    dependencies = [
        ('events', '0002_event_type_no_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassifyImageEvent',
        ),
    ]
