# Generated by Django 4.2.16 on 2024-10-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_classifyimageevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='events_even_type_654a97_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_id'], name='events_even_source__90c628_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['image_id'], name='events_even_image_i_7ccdb3_idx'),
        ),
    ]
