# Generated by Django 4.2.27 on 2026-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_indexes_for_type_source_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='classifier_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
