# Generated by Django 4.2.27 on 2026-07-27 00:20

from django.db import migrations
from django.db.models import F


def populate_creator_fk(apps, schema_editor):
    """
    Populate the newly added creator foreign-key field, based on the existing
    creator integer-ID field.
    """
    User = apps.get_model('auth', 'User')
    Event = apps.get_model('events', 'Event')

    events_with_creator = Event.objects.filter(creator_id__isnull=False)

    # Since the foreign key field will actually check for valid FKs, ensure
    # that the IDs going into the field are valid User IDs.
    #
    # We're just hoping this won't be too onerous in production, based on the
    # fact that User deletion has only been possible manually up to this point
    # (therefore there shouldn't have been too many deletions).
    #
    # Tip: in advance of this migration, you could open manage.py shell and
    # query for AnnotationUploadEvents' creator_id values, if you're sure
    # that's the only type of event with non-null creator_id. That should be
    # faster than querying for all Events' creator_id values.
    # The latter query could currently be slow because Events aren't yet
    # indexed by creator ID, and there could be a LOT of ClassifyImageEvents
    # to sift through. So that's something you'd only hope to run as a final
    # sanity check, rather than something to run repeatedly.
    distinct_creator_ids = events_with_creator.values_list(
        'creator_id', flat=True).distinct()
    for creator_id in distinct_creator_ids:
        try:
            User.objects.get(pk=creator_id)
        except User.DoesNotExist:
            raise RuntimeError(
                f"User of ID {creator_id} doesn't exist. Delete the Events"
                " with this creator_id, then re-run this migration.")

    events_with_creator.update(creator_new_id=F('creator_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_add_creator_fk'),
    ]

    operations = [
        migrations.RunPython(
            populate_creator_fk, migrations.RunPython.noop),
    ]
