# Generated by Django 4.2.27 on 2026-07-27 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_populate_creator_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator_id',
        ),
    ]
