# Generated by Django 4.2.27 on 2026-07-27 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_remove_old_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator_new',
            new_name='creator',
        ),
    ]
