# Generated by Django 4.2.27 on 2026-04-26 10:19
# (and then heavily manually edited to reduce operations)

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_squashed_0022_job_classifier_populate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('finish_date', models.DateTimeField(null=True, verbose_name='Date finished')),
            ],
        ),
        migrations.CreateModel(
            name='ApiJobUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_core.apijob')),
                ('order_in_parent', models.PositiveIntegerField()),
                ('internal_job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='jobs.job')),
                ('request_json', models.JSONField()),
                ('result_json', models.JSONField(null=True)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='apijobunit',
            constraint=models.UniqueConstraint(fields=('parent', 'order_in_parent'), name='unique_order_within_parent'),
        ),
        migrations.CreateModel(
            name='UserApiLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_active_jobs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User API Limits',
            },
        ),
    ]
