# Generated by Django 4.2.16 on 2025-02-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0009_use_new_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='apijobunit',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
