# Generated by Django 4.2.16 on 2025-02-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0011_userapilimits'),
    ]

    operations = [
        migrations.AddField(
            model_name='apijob',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name='Date finished'),
        ),
    ]
