# Generated by Django 4.2.27 on 2026-04-26 08:13
# (and then heavily manually edited to reduce operations)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
        ('vision_backend', '0001_squashed_0036_sourceclassifieroptions_populate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('arg_identifier', models.CharField(blank=True, max_length=100)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('classifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('result_message', models.CharField(blank=True, max_length=5000)),
                ('attempt_number', models.IntegerField(default=1)),
                ('persist', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('scheduled_start_date', models.DateTimeField(null=True, verbose_name='Scheduled start date')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_progress'])), fields=('job_name', 'arg_identifier'), name='unique_incomplete_jobs'),
        ),
    ]
