# Generated by Django 4.1.10 on 2023-11-19 23:57

from django.db import migrations


def port_job_names(apps, port_spec):
    Job = apps.get_model('jobs', 'Job')

    for job in Job.objects.filter(job_name__in=list(port_spec.keys())):
        # Use update() so we can set the modify date to the existing value
        # rather than having it auto-set to the current date.
        Job.objects.filter(pk=job.pk).update(
            job_name=port_spec[job.job_name], modify_date=job.modify_date)


def deploy_to_classify_image(apps, schema_editor):
    port_job_names(apps, dict(
        deploy='classify_image',
    ))


def classify_image_to_deploy(apps, schema_editor):
    port_job_names(apps, dict(
        classify_image='deploy',
    ))


class Migration(migrations.Migration):
    """
    At some point the deploy job in the code was renamed to classify_image, but
    the existing Jobs in the database were not renamed accordingly.
    """

    dependencies = [
        ('jobs', '0012_status_port_values_redo'),
    ]

    operations = [
        migrations.RunPython(
            deploy_to_classify_image,
            classify_image_to_deploy,
        )
    ]
