# Generated by Django 4.1.10 on 2024-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='job',
            name='unique_running_jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_start_date',
            field=models.DateTimeField(null=True, verbose_name='Scheduled start date'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_progress'])), fields=('job_name', 'arg_identifier'), name='unique_incomplete_jobs'),
        ),
    ]
