# Generated by Django 4.2.16 on 2024-10-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_source_fk_restore_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
