# Generated by Django 4.2.27 on 2026-04-28 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Classifier.train_job -> Job.classifier, part 2 of 4.
    """

    dependencies = [
        ('vision_backend', '0033_classifier_train_job_related_name'),
        ('jobs', '0020_big_auto_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='classifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier'),
        ),
    ]
