# Generated by Django 4.2.27 on 2026-04-28 07:42

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_job_classifier(apps, schema_editor):
    """
    Populate the Job model's classifier field using the Classifier.train_job
    value.
    """
    Job = apps.get_model('jobs', 'Job')
    Classifier = apps.get_model('vision_backend', 'Classifier')

    all_classifiers = Classifier.objects.filter(
        train_job__isnull=False).select_related('train_job')
    jobs_to_update = []

    for classifier in tqdm(all_classifiers, disable=settings.TQDM_DISABLE):
        classifier.train_job.classifier = classifier
        jobs_to_update.append(classifier.train_job)

    Job.objects.bulk_update(jobs_to_update, ['classifier'])


def populate_classifier_train_job(apps, schema_editor):
    """
    Populate the Classifier model's train_job field using the Job.classifier
    value.
    """
    Job = apps.get_model('jobs', 'Job')
    Classifier = apps.get_model('vision_backend', 'Classifier')

    jobs_with_classifiers = Job.objects.filter(
        classifier__isnull=False).select_related('classifier')
    classifiers_to_update = []

    for job in tqdm(jobs_with_classifiers, disable=settings.TQDM_DISABLE):
        job.classifier.train_job = job
        classifiers_to_update.append(job.classifier)

    Classifier.objects.bulk_update(classifiers_to_update, ['train_job'])


class Migration(migrations.Migration):
    """
    Classifier.train_job -> Job.classifier, part 3 of 4.
    """

    dependencies = [
        ('jobs', '0021_job_classifier'),
    ]

    operations = [
        migrations.RunPython(
            populate_job_classifier,
            populate_classifier_train_job,
            elidable=True,
        ),
    ]
