# Generated by Django 4.2.27 on 2026-04-27 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_squashed_0022_job_classifier_populate'),
        ('vision_backend', '0001_squashed_0036_sourceclassifieroptions_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('PENDING', 'PENDING'), ('RUNNABLE', 'RUNNABLE'), ('STARTING', 'STARTING'), ('RUNNING', 'RUNNING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='SUBMITTED', max_length=12)),
                ('batch_token', models.CharField(max_length=128, null=True)),
                ('spec_level', models.CharField(choices=[('medium', 'MEDIUM'), ('high', 'HIGH')], default='', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('internal_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
