# Generated by Django 4.2.27 on 2026-04-26 06:50
# (and then heavily manually edited to reduce operations)

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('sources', '0001_initial'), ('sources', '0002_create_source'), ('sources', '0003_source_fk_app_change'), ('sources', '0004_source_fk_restore_constraint'), ('sources', '0005_source_contenttype_app_change'), ('sources', '0006_remove_long_help_texts'), ('sources', '0007_source_annotation_area_non_null'), ('sources', '0008_source_annoarea_and_pointgen_defaults'), ('sources', '0009_add_deployed_classifier_and_more'), ('sources', '0010_populate_deployed_classifier'), ('sources', '0011_sourceinvite_big_auto_field'), ('sources', '0012_source_big_auto_field'), ('sources', '0013_remove_source_confidence_threshold_and_more')]

    initial = True

    dependencies = [
        ('labels', '0001_squashed_0007_label_big_auto_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('visibility', models.CharField(choices=[('b', 'Public'), ('v', 'Private')], default='b', max_length=1)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('description', models.TextField()),
                ('affiliation', models.CharField(max_length=200)),
                ('key1', models.CharField(default='Aux1', max_length=50, verbose_name='Aux. metadata 1')),
                ('key2', models.CharField(default='Aux2', max_length=50, verbose_name='Aux. metadata 2')),
                ('key3', models.CharField(default='Aux3', max_length=50, verbose_name='Aux. metadata 3')),
                ('key4', models.CharField(default='Aux4', max_length=50, verbose_name='Aux. metadata 4')),
                ('key5', models.CharField(default='Aux5', max_length=50, verbose_name='Aux. metadata 5')),
                ('default_point_generation_method', models.CharField(default='m_30', max_length=50, verbose_name='Point generation method')),
                ('image_annotation_area', models.CharField(default='0;100;0;100', max_length=50, verbose_name='Default image annotation area')),
                ('cpce_code_filepath', models.CharField(default='', max_length=1000, verbose_name='Local absolute path to the CPCe code file')),
                ('cpce_image_dir', models.CharField(default='', help_text='Ending slash can be present or not', max_length=1000, verbose_name='Local absolute path to the directory with image files')),
                ('longitude', models.CharField(blank=True, max_length=20)),
                ('latitude', models.CharField(blank=True, max_length=20)),
                ('labelset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='labels.labelset')),
            ],
            options={
                'permissions': (('source_view', 'View'), ('source_edit', 'Edit'), ('source_admin', 'Admin')),
            },
        ),
        migrations.CreateModel(
            name='SourceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_perm', models.CharField(choices=[('source_view', 'View'), ('source_edit', 'Edit'), ('source_admin', 'Admin')], max_length=50)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
            options={
                'unique_together': {('recipient', 'source')},
            },
        ),
    ]
