# Generated by Django 4.1.10 on 2024-04-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0038_rename_source_table'),
        ('sources', '0003_source_fk_app_change'),
    ]

    operations = [
        # Re-enable sources.source FK constraints.
        migrations.AlterField(
            model_name='sourceinvite',
            name='source',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source', db_constraint=True),
        ),
    ]
