# Generated by Django 4.2.27 on 2026-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_populate_deployed_classifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceinvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
