# Generated by Django 4.2.27 on 2026-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Source has FK references in large tables in production, so here we give
    Source its own BigAutoField migration to isolate its migration-runtime
    concerns.

    Dangling foreign keys (i.e. referencing a deleted object) will make this
    migration fail, requiring the migration to start over from the beginning.
    So, check for dangling FKs before migrating. To do so, you can run
    these statements in dbshell and ensure they come up with 0 rows:

    select * from annotations_annotation where not exists(select from sources_source where sources_source.id = annotations_annotation.source_id);
    select * from annotations_imageannotationinfo where not exists(select from sources_source where sources_source.id = annotations_imageannotationinfo.source_id);
    select * from annotations_annotationtoolaccess where not exists(select from sources_source where sources_source.id = annotations_annotationtoolaccess.source_id);
    select * from calcification_calcifyratetable where calcification_calcifyratetable.source_id is not null and not exists(select from sources_source where sources_source.id = calcification_calcifyratetable.source_id);
    select * from images_image where not exists(select from sources_source where sources_source.id = images_image.source_id);
    select * from images_metadata where not exists(select from sources_source where sources_source.id = images_metadata.source_id);
    select * from jobs_job where jobs_job.source_id is not null and not exists(select from sources_source where sources_source.id = jobs_job.source_id);
    select * from sources_sourceinvite where not exists(select from sources_source where sources_source.id = sources_sourceinvite.source_id);
    select * from vision_backend_classifier where not exists(select from sources_source where sources_source.id = vision_backend_classifier.source_id);
    select * from vision_backend_score where not exists(select from sources_source where sources_source.id = vision_backend_score.source_id);

    See images 0053 and 0054 comments for examples of how to get dangling FKs
    in the ORM in order to deal with them.
    """

    dependencies = [
        ('sources', '0011_sourceinvite_big_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
