# Generated by Django 4.2.27 on 2026-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_sourceinvite_big_auto_field'),
    ]

    operations = [
        # Source has FK references in large tables in production, so it
        # gets its own BigAutoField migration to isolate its migration-runtime
        # concerns.
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
