# Generated by Django 4.2.27 on 2026-04-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_source_big_auto_field'),
        ('vision_backend', '0036_sourceclassifieroptions_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='confidence_threshold',
        ),
        migrations.RemoveField(
            model_name='source',
            name='deployed_classifier',
        ),
        migrations.RemoveField(
            model_name='source',
            name='deployed_source_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='feature_extractor_setting',
        ),
        migrations.RemoveField(
            model_name='source',
            name='trains_own_classifiers',
        ),
    ]
