# Generated by Django 4.2.27 on 2026-04-26 10:26
# (and then heavily manually edited to reduce operations)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('calcification', '0001_initial'), ('calcification', '0002_use_new_jsonfield'), ('calcification', '0003_source_fk_app_change'), ('calcification', '0004_source_fk_restore_constraint'), ('calcification', '0005_big_auto_fields')]

    initial = True

    dependencies = [
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcifyRateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rates_json', models.JSONField()),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('region', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Calcification rate table',
            },
        ),
        migrations.AddConstraint(
            model_name='calcifyratetable',
            constraint=models.UniqueConstraint(fields=('source', 'name'), name='unique_name_within_source'),
        ),
    ]
