# Generated by Django 4.2.27 on 2026-02-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcification', '0004_source_fk_restore_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcifyratetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
