# Generated by Django 4.2.27 on 2026-04-26 04:58
# (and then heavily manually edited to reduce operations)

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_indexes_for_type_source_image'),
        ('images', '0001_squashed_0054_image_big_auto_field'),
        ('labels', '0001_squashed_0007_label_big_auto_field'),
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
        ('vision_backend',
         '0001_squashed_0036_sourceclassifieroptions_populate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_date', models.DateTimeField(auto_now=True)),
                ('point', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.point')),
                ('image', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('user', models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('robot_version', models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier')),
                ('label', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='labels.label')),
                ('source', models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='annoinfo', to='images.image')),
                ('source', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('classifier', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier')),
                ('status', models.CharField(choices=[('unclassified', 'Unclassified'), ('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed')], default='unclassified', max_length=30)),
                ('last_annotation', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='annotations.annotation')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationUploadEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='AnnotationToolAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_date', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('source', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationToolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('point_marker', models.CharField(choices=[('crosshair', 'Crosshair'), ('circle', 'Circle'), ('crosshair and circle', 'Crosshair and circle'), ('box', 'Box')], default='crosshair', max_length=30)),
                ('point_marker_size', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('point_marker_is_scaled', models.BooleanField(default=False)),
                ('point_number_size', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('point_number_is_scaled', models.BooleanField(default=False)),
                ('unannotated_point_color', models.CharField(default='FFFF00', max_length=6, verbose_name='Not annotated point color')),
                ('robot_annotated_point_color', models.CharField(default='FFFF00', max_length=6, verbose_name='Unconfirmed point color')),
                ('human_annotated_point_color', models.CharField(default='8888FF', max_length=6, verbose_name='Confirmed point color')),
                ('selected_point_color', models.CharField(default='00FF00', max_length=6)),
                ('show_machine_annotations', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image', 'user'], name='annotation_to_img_usr_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image', 'label', 'user'], name='annotation_to_img_lbl_usr_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['label', 'source'], name='annotation_to_lbl_src_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'user', 'robot_version'], name='annotation_to_src_usr_rbtv_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'label', 'user'], name='annotation_to_src_lbl_usr_i'),
        ),
        migrations.AddIndex(
            model_name='imageannotationinfo',
            index=models.Index(fields=['source', 'status'], name='annoinfo_to_src_status_i'),
        ),
    ]
