# Generated by Django 4.2.16 on 2024-10-19 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0027_sourcecheckrequestevent'),
        ('annotations', '0025_source_fk_restore_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotationinfo',
            name='classifier',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier'),
        ),
    ]
