# Generated by Django 4.2.16 on 2024-12-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_indexes_for_type_source_image'),
        ('annotations', '0027_annoinfo_populate_classifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationUploadEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
