# Generated by Django 4.2.16 on 2025-06-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0029_annotation_remove_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image', 'user'], name='annotation_to_img_usr_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image', 'label', 'user'], name='annotation_to_img_lbl_usr_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['label', 'source'], name='annotation_to_lbl_src_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'user', 'robot_version'], name='annotation_to_src_usr_rbtv_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'label', 'user'], name='annotation_to_src_lbl_usr_i'),
        ),
    ]
