# Generated by Django 4.2.16 on 2025-07-13 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    First migration out of a sequence of 3 for creating an
    ImageAnnotationInfo.source ForeignKey.
    """

    dependencies = [
        ('sources', '0010_populate_deployed_classifier'),
        ('annotations', '0030_annotation_new_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotationinfo',
            name='source',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
    ]
