# Generated by Django 4.2.16 on 2025-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0033_annoinfo_source_schema2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='imageannotationinfo',
            index=models.Index(fields=['source', 'status'], name='annoinfo_to_src_status_i'),
        ),
    ]
