# Generated by Django 4.2.16 on 2025-07-13 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_locallabel_unique_label_within_labelset'),
        ('vision_backend', '0027_sourcecheckrequestevent'),
        ('images', '0051_unique_metadata_names_in_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sources', '0010_populate_deployed_classifier'),
        ('annotations', '0034_annoinfo_to_src_status_index'),
    ]

    operations = [
        # Only change in all of these field alterations is db_index=False.
        migrations.AlterField(
            model_name='annotation',
            name='image',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to='labels.label'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='robot_version',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='source',
            field=models.ForeignKey(db_index=False, editable=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.ForeignKey(db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
