# Generated by Django 4.2.27 on 2026-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0035_annotation_fields_db_index_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtoolaccess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annotationtoolsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageannotationinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
