# Generated by Django 4.2.27 on 2026-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_easier_big_auto_fields'),
    ]

    operations = [
        # Annotation has FK references in large tables in production, so it
        # gets its own BigAutoField migration to isolate its migration-runtime
        # concerns.
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
