# Generated by Django 4.2.27 on 2026-06-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_squashed_0037_annotation_big_auto_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='scrambled_sort_key',
            field=models.SmallIntegerField(default=0),
        ),
    ]
