# Generated by Django 4.2.27 on 2026-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0038_annotation_scrambled_sort_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
