# Generated by Django 4.2.27 on 2026-06-18 08:02

from django.conf import settings
from django.db import migrations
from django.db.models import Q


def populate_confirmed_field(apps, schema_editor):
    """
    Populate the newly added confirmed field, based on the existing user field.
    """
    User = apps.get_model('auth', 'User')
    robot_user_id = User.objects.get(username=settings.ROBOT_USERNAME).pk

    Annotation = apps.get_model('annotations', 'Annotation')
    Annotation.objects.all().update(
        confirmed=~Q(user=robot_user_id)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_squashed_0012_field_string_attributes_to_unicode'),
        ('annotations', '0039_annotation_confirmed'),
    ]

    operations = [
        migrations.RunPython(
            populate_confirmed_field, migrations.RunPython.noop),
    ]
