# Generated by Django 4.2.27 on 2026-06-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_annotation_confirmed_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='confirmed',
            field=models.BooleanField(),
        ),
    ]
