# Generated by Django 4.2.27 on 2026-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_annotation_confirmed_non_null'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_to_img_usr_i',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_to_img_lbl_usr_i',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_to_lbl_src_i',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='annotation_to_src_lbl_usr_i',
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['image', 'confirmed'], name='annotation_to_img_confirm_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['label', 'confirmed', 'scrambled_sort_key'], name='anno_to_lbl_confirm_hsh_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'label', 'confirmed'], name='anno_to_src_lbl_confirm_i'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['source', 'scrambled_sort_key'], name='annotation_to_src_hsh_i'),
        ),
    ]
