# Generated by Django 4.2.27 on 2026-07-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0001_squashed_0036_sourceclassifieroptions_populate'),
        ('annotations', '0042_remove_annotation_annotation_to_img_usr_i_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='robot_version',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vision_backend.classifier'),
        ),
    ]
