# Generated by Django 4.2.27 on 2026-04-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('vision_backend', '0001_squashed_0011_features_image_non_null'), ('vision_backend', '0002_classifier_status'), ('vision_backend', '0003_populate_classifier_status'), ('vision_backend', '0004_remove_classifier_valid'), ('vision_backend', '0005_classifier_status_new_choice'), ('vision_backend', '0006_score_bigautofield'), ('vision_backend', '0007_batchjob_jobtoken_nullable'), ('vision_backend', '0008_batchjob_add_internaljob'), ('vision_backend', '0009_batchjob_delete_old_completed'), ('vision_backend', '0010_batchjob_internaljob_required'), ('vision_backend', '0011_alter_features_model_was_cashed'), ('vision_backend', '0012_rename_model_was_cashed_features_model_was_cached'), ('vision_backend', '0013_classifier_train_job'), ('vision_backend', '0014_remove_features_classified'), ('vision_backend', '0015_features_extractor_loaded_remotely'), ('vision_backend', '0016_populate_extractor_loaded_remotely'), ('vision_backend', '0017_remove_features_model_was_cached'), ('vision_backend', '0018_remove_features_runtime_core'), ('vision_backend', '0019_batchjob_spec_level'), ('vision_backend', '0020_features_has_rowcols'), ('vision_backend', '0021_features_populate_has_rowcols'), ('vision_backend', '0022_source_fk_app_change'), ('vision_backend', '0023_source_fk_restore_constraint'), ('vision_backend', '0024_features_add_extractor'), ('vision_backend', '0025_features_populate_extractor'), ('vision_backend', '0026_classifyimageevent'), ('vision_backend', '0027_sourcecheckrequestevent'), ('vision_backend', '0028_easier_big_auto_fields'), ('vision_backend', '0029_score_auto_created_auto_field'), ('vision_backend', '0030_classifier_big_auto_field'), ('vision_backend', '0031_rename_batchjob_table'), ('vision_backend', '0032_delete_batchjob'), ('vision_backend', '0033_classifier_train_job_related_name'), ('vision_backend', '0034_remove_classifier_train_job'), ('vision_backend', '0035_sourceclassifieroptions'), ('vision_backend', '0036_sourceclassifieroptions_populate')]

    initial = True

    dependencies = [
        ('events', '0003_delete_classifyimageevent'),
        ('images', '0001_squashed_0054_image_big_auto_field'),
        ('labels', '0001_squashed_0007_label_big_auto_field'),
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_train', models.BigIntegerField(default=0)),
                ('nbr_train_images', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('accuracy', models.FloatField(null=True)),
                ('epoch_ref_accuracy', models.CharField(max_length=512, null=True)),
                ('status', models.CharField(choices=[('PN', 'Training pending'), ('UQ', 'Declined because the training labelset only had one unique label'), ('ER', 'Training got an error'), ('RJ', "Rejected because accuracy didn't improve enough"), ('AC', 'Accepted as new classifier')], default='PN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.BooleanField(default=False)),
                ('runtime_total', models.IntegerField(null=True)),
                ('extracted_date', models.DateTimeField(null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('extractor_loaded_remotely', models.BooleanField(null=True)),
                ('has_rowcols', models.BooleanField(null=True)),
                ('extractor', models.CharField(blank=True, choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)'), ('dummy', 'Dummy')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.point')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceClassifierOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence threshold (%)')),
                ('trains_own_classifiers', models.BooleanField(default=True, verbose_name='Source trains its own classifiers')),
                ('deployed_source_id', models.BigIntegerField(blank=True, null=True)),
                ('feature_extractor_setting', models.CharField(choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)')], default='efficientnet_b0_ver1', max_length=50, verbose_name='Feature extractor')),
                ('deployed_classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploying_sources', to='vision_backend.classifier')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_options', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='ClassifyImageEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='SourceCheckRequestEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
