# Generated by Django 4.2.27 on 2026-04-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_delete_classifyimageevent'),
        ('images', '0001_squashed_0054_image_big_auto_field'),
        ('labels', '0001_squashed_0007_label_big_auto_field'),
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime_train', models.BigIntegerField(default=0)),
                ('nbr_train_images', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('accuracy', models.FloatField(null=True)),
                ('epoch_ref_accuracy', models.CharField(max_length=512, null=True)),
                ('status', models.CharField(choices=[('PN', 'Training pending'), ('UQ', 'Declined because the training labelset only had one unique label'), ('ER', 'Training got an error'), ('RJ', "Rejected because accuracy didn't improve enough"), ('AC', 'Accepted as new classifier')], default='PN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted', models.BooleanField(default=False)),
                ('runtime_total', models.IntegerField(null=True)),
                ('extracted_date', models.DateTimeField(null=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('extractor_loaded_remotely', models.BooleanField(null=True)),
                ('has_rowcols', models.BooleanField(null=True)),
                ('extractor', models.CharField(blank=True, choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)'), ('dummy', 'Dummy')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.label')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.point')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceClassifierOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence threshold (%)')),
                ('trains_own_classifiers', models.BooleanField(default=True, verbose_name='Source trains its own classifiers')),
                ('deployed_source_id', models.BigIntegerField(blank=True, null=True)),
                ('feature_extractor_setting', models.CharField(choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)')], default='efficientnet_b0_ver1', max_length=50, verbose_name='Feature extractor')),
                ('deployed_classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploying_sources', to='vision_backend.classifier')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_options', to='sources.source')),
            ],
        ),
        migrations.CreateModel(
            name='ClassifyImageEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='SourceCheckRequestEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
