# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-22 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0006_batchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='job_token',
            field=models.CharField(max_length=256),
        ),
    ]
