# Generated by Django 4.1.10 on 2023-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0018_remove_features_runtime_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='spec_level',
            field=models.CharField(choices=[('medium', 'MEDIUM'), ('high', 'HIGH')], default='', max_length=20),
        ),
    ]
