# Generated by Django 4.1.10 on 2024-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0019_batchjob_spec_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='has_rowcols',
            field=models.BooleanField(null=True),
        ),
    ]
