# Generated by Django 4.1.10 on 2024-05-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0023_source_fk_restore_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='extractor',
            field=models.CharField(blank=True, choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)'), ('dummy', 'Dummy')], default='', max_length=50),
        ),
    ]
