# Generated by Django 4.1.10 on 2024-05-15 03:17

from django.db import migrations


def populate_extractor(apps, schema_editor):
    Features = apps.get_model('vision_backend', 'Features')

    all_features = Features.objects.filter(extracted=True)

    # Up to this point, the extractor used is the same as the extractor
    # setting of the image's source. (That may not hold true from now on,
    # which is why we've added the extractor field in the first place.)
    effnet_features = all_features.filter(
        image__source__feature_extractor_setting='efficientnet_b0_ver1')
    effnet_features.update(extractor='efficientnet_b0_ver1')
    vgg16_features = all_features.filter(
        image__source__feature_extractor_setting='vgg16_coralnet_ver1')
    vgg16_features.update(extractor='vgg16_coralnet_ver1')


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0024_features_add_extractor'),
    ]

    operations = [
        migrations.RunPython(populate_extractor, migrations.RunPython.noop),
    ]
