# Generated by Django 4.2.16 on 2024-10-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_classifyimageevent'),
        ('vision_backend', '0025_features_populate_extractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyImageEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
