# Generated by Django 4.2.27 on 2026-02-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0028_easier_big_auto_fields'),
    ]

    operations = [
        # Score has a ton of rows in production, so it gets its own
        # BigAutoField migration to isolate its migration-runtime concerns.
        #
        # That being said, this already had a BigAutoField and now we're only
        # saying the field should be considered auto-created. So it shouldn't
        # have any reason to trigger an operation that cares about the table
        # size. But we're just being on the safe side.
        migrations.AlterField(
            model_name='score',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
