# Generated by Django 4.2.27 on 2026-02-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0029_score_auto_created_auto_field'),
    ]

    operations = [
        # Classifier has FK references in large tables in production, so it
        # gets its own BigAutoField migration to isolate its migration-runtime
        # concerns.
        migrations.AlterField(
            model_name='classifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
