# Generated by Django 4.2.27 on 2026-04-27 07:15

from django.db import migrations


class Migration(migrations.Migration):
    """
    Part of moving the BatchJob model from vision_backend to aws.

    1. Define a database-only rename of the Postgres table (this migration)
    2. Define a state-only model creation (i.e. doesn't actually
       create a Postgres table) in aws
    3. Define a state-only model deletion (i.e. doesn't actually
       delete a Postgres table) in vision_backend
    """

    dependencies = [
        # This migration fails if the batchjob table is already renamed.
        ('jobs', '0020_big_auto_fields'),
        ('sources', '0012_source_big_auto_field'),
        ('vision_backend', '0030_classifier_big_auto_field'),
    ]

    database_operations = [
        # The table name that Django looks for can be confirmed with
        # `BatchJob._meta.db_table`.
        migrations.AlterModelTable('BatchJob', 'aws_batchjob'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations)
    ]
