# Generated by Django 4.2.27 on 2026-04-27 04:08

from django.db import migrations


class Migration(migrations.Migration):
    """
    Part of moving the BatchJob model from vision_backend to aws.

    1. Define a database-only rename of the Postgres table
    2. Define a state-only model creation (i.e. doesn't actually
       create a Postgres table) in aws
    3. Define a state-only model deletion (i.e. doesn't actually
       delete a Postgres table) in vision_backend (this migration)
    """

    dependencies = [
        # Commenting out this dep to make the squash process happy.
        # ('aws', '0001_initial'),
        ('vision_backend', '0031_rename_batchjob_table'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='BatchJob',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
