# Generated by Django 4.2.27 on 2026-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Classifier.train_job -> Job.classifier, part 1 of 4.
    This changes train_job's related_name to something that won't clash with
    the new field.
    """

    dependencies = [
        ('vision_backend', '0032_delete_batchjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='train_job',
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name='classifier_old', to='jobs.job'),
        ),
    ]
