# Generated by Django 4.2.27 on 2026-04-28 07:41

from django.db import migrations


class Migration(migrations.Migration):
    """
    Classifier.train_job -> Job.classifier, part 4 of 4.
    """

    dependencies = [
        ('vision_backend', '0033_classifier_train_job_related_name'),
        ('jobs', '0022_job_classifier_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='train_job',
        ),
    ]
