# Generated by Django 4.2.27 on 2026-04-30 07:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0034_remove_classifier_train_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceClassifierOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Confidence threshold (%)')),
                ('trains_own_classifiers', models.BooleanField(default=True, verbose_name='Source trains its own classifiers')),
                ('deployed_source_id', models.BigIntegerField(blank=True, null=True)),
                ('feature_extractor_setting', models.CharField(choices=[('efficientnet_b0_ver1', 'EfficientNet (default)'), ('vgg16_coralnet_ver1', 'VGG16 (legacy)')], default='efficientnet_b0_ver1', max_length=50, verbose_name='Feature extractor')),
                ('deployed_classifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploying_sources', to='vision_backend.classifier')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_options', to='sources.source')),
            ],
        ),
    ]
