# Generated by Django 4.2.27 on 2026-04-30 07:49

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_classifier_options_fields(apps, schema_editor):
    """
    Create and populate SourceClassifierOptions instances using
    the corresponding Source field values.
    """
    Source = apps.get_model('sources', 'Source')
    SourceClassifierOptions = apps.get_model('vision_backend', 'SourceClassifierOptions')

    all_sources = Source.objects.all()
    options_instances_to_create = []

    for source in tqdm(all_sources, disable=settings.TQDM_DISABLE):
        options_instance = SourceClassifierOptions(
            source=source,
            confidence_threshold=source.confidence_threshold,
            trains_own_classifiers=source.trains_own_classifiers,
            deployed_classifier=source.deployed_classifier,
            deployed_source_id=source.deployed_source_id,
            feature_extractor_setting=source.feature_extractor_setting,
        )
        options_instances_to_create.append(options_instance)

    SourceClassifierOptions.objects.bulk_create(options_instances_to_create)


def populate_source_fields(apps, schema_editor):
    """
    Populate the vision backend related Source fields using
    the SourceClassifierOptions instances' field values.
    """
    Source = apps.get_model('sources', 'Source')
    SourceClassifierOptions = apps.get_model('vision_backend', 'SourceClassifierOptions')

    all_options_instances = SourceClassifierOptions.objects.all()
    sources_to_update = []

    for options in tqdm(all_options_instances, disable=settings.TQDM_DISABLE):
        source = options.source
        source.confidence_threshold = options.confidence_threshold
        source.trains_own_classifiers = options.trains_own_classifiers
        source.deployed_classifier = options.deployed_classifier
        source.deployed_source_id = options.deployed_source_id
        source.feature_extractor_setting = options.feature_extractor_setting
        sources_to_update.append(source)

    Source.objects.bulk_update(
        sources_to_update,
        [
            'confidence_threshold',
            'trains_own_classifiers',
            'deployed_classifier',
            'deployed_source_id',
            'feature_extractor_setting',
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vision_backend', '0035_sourceclassifieroptions'),
    ]

    operations = [
        migrations.RunPython(
            populate_classifier_options_fields,
            populate_source_fields,
            elidable=True,
        ),
    ]
