# Generated by Django 4.2.16 on 2024-12-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_more_concise_regex_validators'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locallabel',
            constraint=models.UniqueConstraint(fields=('global_label', 'labelset'), name='unique_label_within_labelset'),
        ),
    ]
