# Generated by Django 4.2.27 on 2026-02-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_easier_big_auto_fields'),
    ]

    operations = [
        # Label has FK references in large tables in production, so it
        # gets its own BigAutoField migration to isolate its migration-runtime
        # concerns.
        migrations.AlterField(
            model_name='label',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
