# Generated by Django 4.2.27 on 2026-04-26 05:49
# (and then heavily manually edited to reduce operations)

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text
import easy_thumbnails.fields
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_squashed_0013_move_confidence_threshold_etc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', easy_thumbnails.fields.ThumbnailerImageField(height_field='original_height', upload_to=images.models.get_original_image_upload_path, width_field='original_width')),
                ('original_width', models.IntegerField()),
                ('original_height', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload date')),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('point_generation_method', models.CharField(blank=True, max_length=50, verbose_name='How points were generated')),
                ('cpc_content', models.TextField(default='', verbose_name='File content of last .cpc uploaded for this image')),
                ('cpc_filename', models.CharField(default='', max_length=1000, verbose_name='Filename of last .cpc uploaded for this image')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('unprocessable_reason', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
                ('source', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='sources.source')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('photo_date', models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, verbose_name='Date')),
                ('latitude', models.CharField(blank=True, max_length=20, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=20, verbose_name='Longitude')),
                ('depth', models.CharField(blank=True, max_length=45, verbose_name='Depth')),
                ('height_in_cm', models.IntegerField(blank=True, help_text='The number of centimeters of substrate the image covers, from the top of the image to the bottom.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)')),
                ('annotation_area', models.CharField(blank=True, help_text='This defines a rectangle of the image where annotation points are allowed to be generated. If you change this, then new points will be generated for this image, and the old points will be deleted.', max_length=50, null=True, verbose_name='Annotation area')),
                ('camera', models.CharField(blank=True, max_length=200, verbose_name='Camera')),
                ('photographer', models.CharField(blank=True, max_length=45, verbose_name='Photographer')),
                ('water_quality', models.CharField(blank=True, max_length=45, verbose_name='Water quality')),
                ('strobes', models.CharField(blank=True, max_length=200, verbose_name='Strobes')),
                ('framing', models.CharField(blank=True, max_length=200, verbose_name='Framing gear used')),
                ('balance', models.CharField(blank=True, max_length=200, verbose_name='White balance card')),
                ('comments', models.TextField(blank=True, max_length=1000, verbose_name='Comments')),
                ('aux1', models.CharField(blank=True, max_length=50)),
                ('aux2', models.CharField(blank=True, max_length=50)),
                ('aux3', models.CharField(blank=True, max_length=50)),
                ('aux4', models.CharField(blank=True, max_length=50)),
                ('aux5', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux1'), django.db.models.functions.text.Lower('aux2'), django.db.models.functions.text.Lower('aux3'), django.db.models.functions.text.Lower('aux4'), django.db.models.functions.text.Lower('aux5'), name='metadata_to_src_auxes_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux2'), name='metadata_to_src_aux2_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux3'), name='metadata_to_src_aux3_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux4'), name='metadata_to_src_aux4_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux5'), name='metadata_to_src_aux5_i'),
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(models.F('source'), django.db.models.functions.text.Lower('name'), name='unique_metadata_names_in_source'),
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('point_number', models.IntegerField()),
                ('annotation_status', models.CharField(blank=True, max_length=1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
