# Generated by Django 4.1.10 on 2023-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_squashed_0033_remove_image_annotation_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unprocessable_reason',
            field=models.CharField(default='', max_length=200),
        ),
    ]
