# Generated by Django 4.1.10 on 2024-04-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0034_image_unprocessable_reason'),
    ]

    database_operations = [
        # The table name that Django looks for can be confirmed with
        # `SourceInvite._meta.db_table`.
        migrations.AlterModelTable('SourceInvite', 'sources_sourceinvite'),
    ]

    operations = [
        # We are moving the SourceInvite model from one app to
        # another, and to achieve that, we:
        # - Define a database-only rename of the Postgres table, which is what
        #   we're doing here
        # - Define a state-only model creation (i.e. doesn't actually
        #   create a Postgres table) in the sources app
        # - Define a state-only model deletion (i.e. doesn't actually
        #   delete a Postgres table) in this app
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations)
    ]
