# Generated by Django 4.1.10 on 2024-04-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0035_rename_sourceinvite_table'),
        ('sources', '0001_initial'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='SourceInvite',
        ),
    ]

    operations = [
        # We are moving the SourceInvite model from one app to
        # another, and to achieve that, we:
        # - Define a database-only rename of the Postgres table
        # - Define a state-only model creation (i.e. doesn't actually
        #   create a Postgres table) in the sources app
        # - Define a state-only model deletion (i.e. doesn't actually
        #   delete a Postgres table) in this app, which is what we're doing
        #   here
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
