# Generated by Django 4.1.10 on 2024-04-17 03:50

from django.db import migrations


class Migration(migrations.Migration):
    """
    Part of moving the Source model from images to sources.
    See sources/migrations/0002_create_source.py for an explanation.
    """

    dependencies = [
        # Anything that assumes the table is still images_source should
        # be a dependency here. This way, that assumption will hold
        # during those migrations.
        ('annotations', '0024_source_fk_app_change'),
        ('calcification', '0003_source_fk_app_change'),
        ('images', '0037_source_fk_app_change'),
        ('jobs', '0016_source_fk_app_change'),
        ('sources', '0003_source_fk_app_change'),
        ('vision_backend', '0022_source_fk_app_change'),
    ]

    database_operations = [
        # The table name that Django looks for can be confirmed with
        # `Source._meta.db_table`.
        migrations.AlterModelTable('Source', 'sources_source'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations),
    ]
