# Generated by Django 4.1.10 on 2024-04-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0038_rename_source_table'),
    ]

    operations = [
        # Re-enable sources.source FK constraints.
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.source', db_constraint=True),
        ),
    ]
