# Generated by Django 4.1.10 on 2024-04-17 03:07

from django.db import migrations


class Migration(migrations.Migration):
    """
    Part of moving the Source model from images to sources.
    See sources/migrations/0002_create_source.py for an explanation.
    """

    dependencies = [
        ('images', '0039_source_fk_restore_constraint'),
        ('sources', '0005_source_contenttype_app_change'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
