# Generated by Django 4.2.16 on 2025-06-29 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    First migration out of a sequence of 5 for moving the Image.metadata
    ForeignKey to a Metadata.image OneToOneField, similar to what was done
    for Image.features in 2021.

    Advantages of this move:
    - Simplifies and possibly optimizes queries that go across the Image and
      Metadata tables.
    - Simplifies Image deletion logic.
    - Makes the design intent clear: we've been treating Image-Metadata as a
      one-to-one relationship, not many-to-one.
    - Consistency with the similar Features-Image and
      ImageAnnotationInfo-Image relationships.
    """

    dependencies = [
        ('images', '0040_delete_source'),
    ]

    operations = [
        # Ultimately we want the name 'image' and related_name 'metadata', but
        # those names create conflicts with the old Image.metadata field.
        # So we temporarily use '_new' suffixes until we can port the values
        # over and delete the old field.
        migrations.AddField(
            model_name='metadata',
            name='image_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_new', to='images.image'),
        ),
        # Make Image.metadata field nullable, so that migration 0043 can
        # delete the field going forwards and create it (with null values,
        # as there's no other sensible default) going backwards.
        migrations.AlterField(
            model_name='image',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='images.metadata'),
        ),
    ]
