# Generated by Django 4.2.16 on 2025-06-29 09:21

from django.conf import settings
from django.db import migrations
from tqdm import tqdm


def populate_metadata_image(apps, schema_editor):
    """
    Populate the Metadata model's image_new field using the Image.metadata
    value.
    """
    Image = apps.get_model('images', 'Image')
    Metadata = apps.get_model('images', 'Metadata')

    # iterator() helps to not run out of memory with lots of images
    # (like millions).
    all_images = Image.objects.all().iterator(chunk_size=10000)
    for image in tqdm(all_images, disable=settings.TQDM_DISABLE):
        if image.metadata:
            metadata = Metadata.objects.get(pk=image.metadata.pk)
            metadata.image_new = image
            metadata.save()


def populate_image_metadata(apps, schema_editor):
    """
    Populate the Image model's metadata field using the Metadata.image_new
    value (reverse relation is metadata_new).
    """
    Image = apps.get_model('images', 'Image')

    all_images = Image.objects.all().iterator(chunk_size=10000)
    for image in tqdm(all_images, disable=settings.TQDM_DISABLE):
        if image.metadata_new:
            image.metadata = image.metadata_new
            image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0041_metadata_image_onetoone_schema1'),
    ]

    operations = [
        migrations.RunPython(
            populate_metadata_image, populate_image_metadata, elidable=True),
    ]
