# Generated by Django 4.2.16 on 2025-06-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0042_metadata_image_onetoone_data1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='metadata',
        ),
        # Now that the old image.metadata field is gone, the _new suffix
        # can be removed without causing conflicts.
        migrations.RenameField(
            model_name='metadata',
            old_name='image_new',
            new_name='image',
        ),
        # Remove custom related_name, now that the default won't cause
        # conflicts.
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
