# Generated by Django 4.2.16 on 2025-06-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0044_metadata_image_onetoone_data2'),
    ]

    operations = [
        # Make this field non-null, now that it's been populated.
        migrations.AlterField(
            model_name='metadata',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image'),
        ),
    ]
