# Generated by Django 4.2.16 on 2025-07-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    First migration out of a sequence of 3 for creating a Metadata.source
    ForeignKey.
    """

    dependencies = [
        ('sources', '0010_populate_deployed_classifier'),
        ('images', '0045_metadata_image_onetoone_schema3'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='source',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.source'),
        ),
    ]
