# Generated by Django 4.2.16 on 2025-07-04 09:21

from django.db import migrations


def populate_metadata_source(apps, schema_editor):
    """
    Populate the Metadata model's source field using the
    Metadata.image.source value.
    """
    Metadata = apps.get_model('images', 'Metadata')
    Source = apps.get_model('sources', 'Source')

    # Can't use joined fields with F(), like F('image__source'). So we
    # can't update all Metadatas with a single update(). Instead we update
    # one source at a time.
    for source in Source.objects.all():
        Metadata.objects.filter(image__source=source).update(source=source)


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0046_metadata_source_schema1'),
    ]

    operations = [
        migrations.RunPython(
            populate_metadata_source,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
