# Generated by Django 4.2.16 on 2025-07-04 23:12

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0048_metadata_source_schema2'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux1'), django.db.models.functions.text.Lower('aux2'), django.db.models.functions.text.Lower('aux3'), django.db.models.functions.text.Lower('aux4'), django.db.models.functions.text.Lower('aux5'), name='metadata_to_src_auxes_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux2'), name='metadata_to_src_aux2_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux3'), name='metadata_to_src_aux3_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux4'), name='metadata_to_src_aux4_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('aux5'), name='metadata_to_src_aux5_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Lower('name'), name='metadata_to_src_name_i'),
        ),
    ]
