# Generated by Django 4.2.16 on 2025-07-10 23:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0050_rename_dupe_image_names'),
    ]

    operations = [
        # This index is now redundant with the auto-created index from the
        # below constraint.
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_name_i',
        ),
        migrations.AddConstraint(
            model_name='metadata',
            constraint=models.UniqueConstraint(models.F('source'), django.db.models.functions.text.Lower('name'), name='unique_metadata_names_in_source'),
        ),
    ]
