# Generated by Django 4.2.27 on 2026-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0051_unique_metadata_names_in_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
