# Generated by Django 4.2.27 on 2026-02-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Point has FK references in large tables in production, so here we give
    Point its own BigAutoField migration to isolate its migration-runtime
    concerns.

    Dangling foreign keys (i.e. referencing a deleted object) will make this
    migration fail, requiring the migration to start over from the beginning.
    So, check for dangling FKs before migrating. To do so, you can run
    these statements in dbshell and ensure they come up with 0 rows:

    select * from annotations_annotation where not exists(select from images_point where images_point.id = annotations_annotation.point_id);
    select * from vision_backend_score where not exists(select from images_point where images_point.id = vision_backend_score.point_id);

    Generally the thing to do is delete the objects with the dangling FKs.
    This is generally most cleanly done with the Django ORM since it'll run
    cascade deletes, custom delete() logic, etc.
    You can use raw() to get the dangling-FK objects through ORM:

    annos = Annotation.objects.raw("select * from annotations_annotation where not exists(select from images_point where images_point.id = annotations_annotation.point_id)")
    """

    dependencies = [
        ('images', '0052_metadata_big_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
