# Generated by Django 4.2.27 on 2026-02-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0052_metadata_big_auto_field'),
    ]

    operations = [
        # Point has FK references in large tables in production, so it gets its
        # own BigAutoField migration to isolate its migration-runtime concerns.
        migrations.AlterField(
            model_name='point',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
