# Generated by Django 4.2.27 on 2026-02-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Image has FK references in large tables in production, so here we give
    Image its own BigAutoField migration to isolate its migration-runtime
    concerns.

    Dangling foreign keys (i.e. referencing a deleted object) will make this
    migration fail, requiring the migration to start over from the beginning.
    So, check for dangling FKs before migrating. To do so, you can run
    these statements in dbshell and ensure they come up with 0 rows:

    select * from annotations_annotation where not exists(select from images_image where images_image.id = annotations_annotation.image_id);
    select * from annotations_annotationtoolaccess where not exists(select from images_image where images_image.id = annotations_annotationtoolaccess.image_id);
    select * from annotations_imageannotationinfo where not exists(select from images_image where images_image.id = annotations_imageannotationinfo.image_id);
    select * from images_metadata where not exists(select from images_image where images_image.id = images_metadata.image_id);
    select * from images_point where not exists(select from images_image where images_image.id = images_point.image_id);
    select * from vision_backend_features where not exists(select from images_image where images_image.id = vision_backend_features.image_id);
    select * from vision_backend_score where not exists(select from images_image where images_image.id = vision_backend_score.image_id);

    Generally the thing to do is delete the objects with the dangling FKs.
    This is generally most cleanly done with the Django ORM since it'll run
    cascade deletes, custom delete() logic, etc.
    You can use raw() to get the dangling-FK objects through ORM:

    points = Point.objects.raw("select * from images_point where not exists(select from images_image where images_image.id = images_point.image_id)")
    """

    dependencies = [
        ('images', '0053_point_big_auto_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
