# Generated by Django 4.2.27 on 2026-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_squashed_0054_image_big_auto_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['original_file'], name='image_original_file_i', opclasses=['text_pattern_ops']),
        ),
    ]
