# Generated by Django 4.2.27 on 2026-06-29 05:40

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0055_image_image_original_file_i'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_auxes_i',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_aux2_i',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_aux3_i',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_aux4_i',
        ),
        migrations.RemoveIndex(
            model_name='metadata',
            name='metadata_to_src_aux5_i',
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Upper('aux1'), django.db.models.functions.text.Upper('aux2'), django.db.models.functions.text.Upper('aux3'), django.db.models.functions.text.Upper('aux4'), django.db.models.functions.text.Upper('aux5'), name='metadata_to_src_auxes_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Upper('aux2'), name='metadata_to_src_aux2_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Upper('aux3'), name='metadata_to_src_aux3_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Upper('aux4'), name='metadata_to_src_aux4_i'),
        ),
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.db.models.functions.text.Upper('aux5'), name='metadata_to_src_aux5_i'),
        ),
    ]
