# Generated by Django 4.2.27 on 2026-07-10 11:27

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0056_metadata_aux_indexes_upper'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metadata',
            index=models.Index(models.F('source'), django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='text_pattern_ops'), name='metadata_to_src_name_textops_i'),
        ),
    ]
