# Generated by Django 4.2.27 on 2026-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0057_metadata_name_text_ops_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index('source', models.Case(models.When(cpc_content='', then=models.Value(1)), default=models.Value(0)), name='image_source_cpccontentblank_i'),
        ),
    ]
